---
title: "ggplot2"
author: "xm"
date: "06/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# learning ggplot2

We're learning ggplot2.
```{r warning=FALSE}
getwd()
library(tidyverse)

#car_plot = ggplot(data=mpg, aes(x=displ, y=hwy))
#car_plot + geom_point(alpha=0.4)
#car_plot + geom_point(aes(color=class))

#ggplot(data=mpg) + geom_point(mapping=aes(x = displ, y = hwy, shape = class))
#ggplot(data=mpg) + geom_point(mapping=aes(x=cty, y=hwy, size=class, color=fl))
#ggplot(data = mpg) + geom_point(mapping=aes(x = displ, y = hwy, color=cty))
#ggplot(data = mpg) + geom_point(mapping=aes(x = displ, y = hwy, color=displ))
#ggplot(data = mpg) + geom_point(mapping=aes(x = displ, y = hwy, color=displ < 5))
ggplot(data=mpg, aes(x=displ, y=hwy, color=class)) + geom_point() + facet_wrap(~ manufacturer) + theme_bw()
ggplot(data=mpg, aes(x=displ, y=hwy)) + geom_smooth() + geom_point(aes(color=class)) + labs(title="The Test Title", x="the x axe", y= "the y axe") + theme_bw()+ theme(text=element_text(size=16))

my_plot <- ggplot(data=mpg) + geom_bar(aes(x=fl, fill=class), position="dodge") + scale_x_discrete(labels=c("CNG","Diesel", "Ethanol", "Premium", "Regular")) + xlab("Fuel type")
ggsave("name_of_File.png", my_plot, width=15, height=10)


# Notional Parks in California
ca <- read_csv("../data/ca.csv")

# Acadia National Parks
# acadia <- read_csv("../data/acadia.csv")

# Southeast US Notional Parks
# se <- read_csv("../data/se.csv")

# 2016 Visitation for all Pacific West National Parks
# visit_16 <- read_csv("../data/visit_16.csv")

# All Nationally designated sites in Massachusetts
# mass <- read_csv("../data/mass.csv")

```

# plot
```{r}
ggplot(data=ca)
```


